import Head from 'next/head'
import Image from 'next/image'

//components
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import Nav from '../components/Nav'
import Draw from '../components/Draw'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero/>
        <Footer/>
        <Draw/>
        <Nav/>
       
      </main>

      
    </div>
  )
}
